version: '3.8'

services:
  # SQL Server Database for Development
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: thegrind5-db-dev
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - db_dev_data:/var/opt/mssql
    networks:
      - thegrind5-dev-network
    restart: unless-stopped

volumes:
  db_dev_data:

networks:
  thegrind5-dev-network:
    driver: bridge
