version: '3.8'

services:
  # SQL Server Database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: thegrind5-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - thegrind5-network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thegrind5-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=db;User Id=sa;Password=YourStrong@Passw0rd;Database=EventDB;TrustServerCertificate=true;
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - thegrind5-network
    restart: unless-stopped

volumes:
  db_data:

networks:
  thegrind5-network:
    driver: bridge
