// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TheGrind5_EventManagement.Models;

public partial class TicketType
{
    public int TicketTypeId { get; set; }

    public int EventId { get; set; }

    [Required]
    public string TypeName { get; set; }

    [Range(0, double.MaxValue, ErrorMessage = "Price must be non-negative")]
    public decimal Price { get; set; }

    [Range(0, int.MaxValue, ErrorMessage = "Quantity must be non-negative")]
    public int Quantity { get; set; }

    [Range(1, int.MaxValue, ErrorMessage = "MinOrder must be at least 1")]
    public int? MinOrder { get; set; }

    public int? MaxOrder { get; set; }

    [Required]
    public DateTime SaleStart { get; set; }

    [Required]
    public DateTime SaleEnd { get; set; }

    [RegularExpression("^(Active|Inactive)$", ErrorMessage = "Status must be Active or Inactive")]
    public string Status { get; set; }

    public virtual Event Event { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}