// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheGrind5_EventManagement.Models;

public partial class OrderItem
{
    public int OrderItemId { get; set; }

    public int OrderId { get; set; }

    public int TicketTypeId { get; set; }

    public int Quantity { get; set; }

    public string SeatNo { get; set; }

    public string Status { get; set; }

    public virtual Order Order { get; set; }

    public virtual TicketType TicketType { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}