// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TheGrind5_EventManagement.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int CustomerId { get; set; }

    [Range(0, double.MaxValue, ErrorMessage = "Amount must be non-negative")]
    public decimal Amount { get; set; }

    [RegularExpression("^(Pending|Paid|Failed|Cancelled|Refunded)$", ErrorMessage = "Status must be Pending, Paid, Failed, Cancelled, or Refunded")]
    public string Status { get; set; }

    public string PaymentMethod { get; set; }

    public string? VoucherCode { get; set; }

    [Range(0, double.MaxValue, ErrorMessage = "DiscountAmount must be non-negative")]
    public decimal DiscountAmount { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}