// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheGrind5_EventManagement.Models;

public partial class TicketType
{
    public int TicketTypeId { get; set; }

    public int EventId { get; set; }

    public string TypeName { get; set; }

    public decimal Price { get; set; }

    public int Quantity { get; set; }

    public int? MinOrder { get; set; }

    public int? MaxOrder { get; set; }

    public DateTime SaleStart { get; set; }

    public DateTime SaleEnd { get; set; }

    public string Status { get; set; }

    public virtual Event Event { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}