// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TheGrind5_EventManagement.Models;

public partial class Ticket
{
    public int TicketId { get; set; }

    public int TicketTypeId { get; set; }

    public int? OrderItemId { get; set; }

    [Required]
    public string SerialNumber { get; set; }

    [RegularExpression("^(Available|Assigned|Used|Refunded)$", ErrorMessage = "Status must be Available, Assigned, Used, or Refunded")]
    public string Status { get; set; }

    public DateTime IssuedAt { get; set; }

    public DateTime? UsedAt { get; set; }

    public DateTime? RefundedAt { get; set; }

    public virtual OrderItem OrderItem { get; set; }

    public virtual TicketType TicketType { get; set; }
}