// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheGrind5_EventManagement.Models;

public partial class Payment
{
    public int TransactionId { get; set; }

    public int OrderId { get; set; }

    public decimal Amount { get; set; }

    public string Method { get; set; }

    public string Status { get; set; }

    public DateTime PaymentDate { get; set; }

    public virtual Order Order { get; set; }
}